export const coffeData = [
  {
    id: 1,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.99,
    image: 'Type=Americano.png',
    tags: ['Tradicional'],
  },
  {
    id: 2,
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.99,
    image: 'Type=Capuccino.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.99,
    image: 'Type=Expresso Cremoso.png',
    tags: ['Tradicional'],
  },
  {
    id: 4,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.99,
    image: 'Type=Irlandês.png',
    tags: ['Especial', 'Alcoólico'],
  },
  {
    id: 5,
    name: 'Mochaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.99,
    image: 'Type=Mochaccino.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 6,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.99,
    image: 'Type=Expresso Gelado.png',
    tags: ['Tradicional', 'Gelado'],
  },
  {
    id: 7,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.99,
    image: 'Type=Chocolate Quente.png',
    tags: ['Especial', 'Com leite'],
  },
  {
    id: 8,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.99,
    image: 'Type=Expresso.png',
    tags: ['Tradicional'],
  },
  {
    id: 9,
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.99,
    image: 'Type=Latte.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 10,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.99,
    image: 'Type=Árabe.png',
    tags: ['Especial'],
  },
  {
    id: 11,
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.99,
    image: 'Type=Café com Leite.png',
    tags: ['Tradicional', 'Com leite'],
  },
  {
    id: 12,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.99,
    image: 'Type=Cubano.png',
    tags: ['Especial', 'Alcoólico', 'Gelado'],
  },
  {
    id: 13,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.99,
    image: 'Type=Havaiano.png',
    tags: ['Especial'],
  },
  {
    id: 14,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.99,
    image: 'Type=Macchiato.png',
    tags: ['Tradicional', 'Com leite'],
  },
]
